In [1]:
import wittgenstein3 as lw3
import wittgenstein as lw
import pandas as pd
import numpy as np
import functions
from sklearn.model_selection import StratifiedKFold
import pickle
import math

In [2]:
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV, cross_val_score, StratifiedKFold, cross_validate, train_test_split

In [8]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
cv = StratifiedKFold(10)

import random
random.seed(25)

iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.Series(iris.target)
pos_class = 2
y = y.map(lambda x: 1 if x==pos_class else 0)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
functions.acc_rate_with_param_selection(pd.concat([X,y], axis=1), 0, 1)

KeyboardInterrupt: 

In [55]:
functions.param_selection(pd.concat([X,y], axis=1), 0, 1)

0.6

In [45]:
ripper_clf = lw3.RIPPER(k=2, n_discretize_bins = 10, W = 0.5)

In [46]:
ripper_clf.fit(pd.concat([X_train,y_train], axis=1), class_feat=0, pos_class=1)

In [47]:
ripper_clf.score(X_test, y_test)

1.0

In [7]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Length: 150, dtype: int32

In [4]:
pd.concat([X,y], axis=1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     0  
0    0  
1    0  
2    0  
3    0  
4    0  
..  ..  
145  1  
146  1  
147  1  
148  1  
149  1  

[150 rows x 5 columns]

In [13]:
y_hat = ripper_clf.predict(X_test)

In [12]:
_, m=functions.param_selection(pd.concat([X_train,y_train], axis=1), class_feat=0, pos_class=1, return_model = True)

In [10]:
functions.acc_rate(pd.concat([X_train,y_train], axis=1), class_feat = 0, pos_class=1, metrics = ['accuracy', 'f1'])

{'accuracy': 0.9971644612476372, 'f1': 1.0985444019754216}

In [11]:
functions.accuracy(pd.concat([X_train,y_train], axis=1), class_feat = 0, pos_class = 1, metrics = ['accuracy', 'f1'])

{'accuracy': 0.8858333333333335, 'f1': 0.8149471070724941}

In [13]:
m.score(X_test, y_test)

0.9666666666666667

In [38]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
cv = StratifiedKFold()

In [33]:
cv.n_splits

5

In [36]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.mean(x, axis = 1)

array([2., 5.])

In [10]:
with open('datasets_classlabels.pkl', 'rb') as fp:
    DFs = pickle.load(fp)

In [14]:
DFs['names']

['thyroid',
 'audiology',
 'autism',
 'adult',
 'arrhythmia',
 'chess king-rook vs king pawn',
 'algerian forest fires',
 'cryotherapy',
 'diabetes',
 'heart failure',
 'students performance',
 'immunotherapy',
 'firewall',
 'Las Vegas clubs']

In [15]:
DFs['xgb_accuracy']

[0.8971399193387374,
 0.96,
 1.0,
 0.8716523341523341,
 0.8296618357487923,
 0.9689958855799373,
 0.7925000000000001,
 0.9222222222222223,
 0.9653846153846153,
 0.8165517241379311,
 0.6385714285714286,
 0.8111111111111111,
 0.9997558393495891,
 0.531529411764706]

In [6]:
def acc_rate_with_param_selection(df,
                                  class_feat, 
                                  pos_class, 
                                  cv_outer = 10,
                                  cv_inner = 5,
                                  param = 'W',
                                  W = None,
                                  budget = 15,
                                  metrics = [accuracy_score],
                                  n_rep = 10):
    # First dummify your categorical features and booleanize your class values to make sklearn happy
    X = df.loc[:,df.columns != class_feat]
    X = pd.get_dummies(X, columns=X.select_dtypes('object').columns)
    y = df[class_feat]
    y = y.map(lambda x: 1 if x==pos_class else 0)
                
    # Set the parameter grid for W and define an array to contain all scores
    acc_standard = np.zeros((n_rep, len(metrics)))
    acc_improved = np.zeros((n_rep, len(metrics)))
    p_grid = np.arange(0.1, 1, 0.1)

    for i in range(n_rep):
        cv_out = StratifiedKFold(cv_outer)
        cv_in = StratifiedKFold(cv_inner)
        scores_run_stand = np.zeros((len(metrics), cv_outer.n_splits))
        scores_run = np.zeros((len(metrics, cv_outer.n_splits)))

SyntaxError: unexpected EOF while parsing (<ipython-input-6-31f181e38cb2>, line 26)

In [ ]:
 for train_ix, test_ix in cv_outer.split(X, y):
            # Split data
            X_train, X_test = X[train_ix, :], X[test_ix, :]
            y_train, y_test = y[train_ix], y[test_ix]

            # Define the models, train standard RIPPERk on the training set
            ripper_clf = lw4.RIPPER(k=2)
            ripper_standard = lw.RIPPER(k=2)
            ripper_standard.fit(pd.concat([X_train,y_train], axis=1), class_feat = 0)

            # Execute search for best W and return the best model too
            best_W, best_model = param_selection(df = pd.concat([X_train,y_train], axis=1), 
                                                    class_feat = class_feat, 
                                                    pos_class = pos_class,
                                                    return_model = True)

            # Predict the values of the test set and compute scores
            y_hat_stand = ripper_standard.predict(y_test)
            y_hat = ripper_clf.predict(y_test)  

            for j in range(len(metrics)):
                metric = metrics[j]
                scores_run_stand[j,k] = metric(y_hat_stand, y_test)
                scores_run[j,k] = metric(y_hat, y_test)

            k += 1
                              
                              
        # store the result
        acc_standard[i,] = np.mean(scores_run_stand, axis = 1)
        acc_improved[i,] = np.mean(scores_run, axis = 1)
                              
                              
    acc_rate = acc_improved / acc_standard
    output = np.mean(acc_rate, axis = 0)
    labels = [str(metric) for metric in metrics]
                              
    return dict(zip(labels, output))
                              